# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x0emessageservice\"\xe8\x01\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x12\n\nbig_number\x18\x03 \x01(\x03\x12\x17\n\x0funsigned_number\x18\x04 \x01(\r\x12\x16\n\x0erepeated_field\x18\x05 \x03(\t\x12?\n\tmap_field\x18\x06 \x03(\x0b\x32,.messageservice.MessageRequest.MapFieldEntry\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"B\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06nested\x18\x03 \x01(\t2b\n\x0eMessageService\x12P\n\x0bSendMessage\x12\x1e.messageservice.MessageRequest\x1a\x1f.messageservice.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST_MAPFIELDENTRY']._loaded_options = None
  _globals['_MESSAGEREQUEST_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEREQUEST']._serialized_start=42
  _globals['_MESSAGEREQUEST']._serialized_end=274
  _globals['_MESSAGEREQUEST_MAPFIELDENTRY']._serialized_start=227
  _globals['_MESSAGEREQUEST_MAPFIELDENTRY']._serialized_end=274
  _globals['_MESSAGERESPONSE']._serialized_start=276
  _globals['_MESSAGERESPONSE']._serialized_end=342
  _globals['_MESSAGESERVICE']._serialized_start=344
  _globals['_MESSAGESERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
